### ISSUE TITLE
how to configure use Sql Server

### ISSUE THREAD

**Issue by hoa-nx** [lakhdar/LMS#1]
The current configuration is using InitialMemorySet, I want to use sql server database . Please help me how to do?
thanks

**Comment by lakhdar** [comment]
Hi they,
Juste change that in the web.config file connectionstringe  section and set your SQL server instead  . And don't forget to activate the reapplicationcontext for defaultioccontainer in the appsetting section .
And you are done

**Comment by hoa-nx** [comment]
Thank for reply.
I  changed Web.config in ASP.NET.MVC5.Client project  : 

```
<connectionStrings>
      <!--<add name="Infrastructure.Data.BoundedContext.UnitOfWork.MainBCUnitOfWork" connectionString="Data Source=.\SQLEXPRESS; Initial Catalog=LMSDataBase;Integrated Security=True;User Id=sa;Password=Abc12345;" providerName="System.Data.SqlClient" />-->
   
   <add name="Infrastructure.Data.BoundedContext.UnitOfWork.MainBCUnitOfWork" providerName="System.Data.SqlClient" connectionString="Data Source=NH\SQLEXPRESS;Initial Catalog=LMSDataBase;Integrated Security=False;User Id=sa;Password=12345;MultipleActiveResultSets=True" />
  
</connectionStrings>

```

```
<appSettings>
    <add key="webpages:Version" value="3.0.0.0" />
    <add key="webpages:Enabled" value="false" />
    <add key="ClientValidationEnabled" value="true" />
    <add key="UnobtrusiveJavaScriptEnabled" value="true" />

    <add key="defaultIoCContainer" value="RealAppContext"/>
    <!--<add key="defaultIoCContainer" value="FakeAppContext" />-->

  </appSettings>
```

But not working , 
Is there a migration database?
Can you guide me step by step ?
Sincerely thanks,

**Comment by lakhdar** [comment]
The config seems correct . And what is the error message you get doing that . Maybe the error will guide us !?

**Comment by hoa-nx** [comment]
When I clicked Login or HOME or NEWS or EVENTS ...has an error at angularjs ( bellow image):
![image-1](https://user-images.githubusercontent.com/6762312/42387991-4105f8f0-816e-11e8-92fb-d588cfb77289.png)

Login screen do not display.

At this point, the database has not yet been created.
have to migration database?
Sincerely thanks,

**Comment by lakhdar** [comment]
Oh I see ! This error that prevents DB creation ! As you see in the console log there is a 500 error so a server error . If you put a break point on the login action on the server you will maybe see the exact error and what went wrong

**Comment by hoa-nx** [comment]
I fixed this problem, 
how to logon with admin role?
Sincerely thanks,

**Comment by lakhdar** [comment]
Just look at appdata folder you LL find all the login you need

**Comment by hoa-nx** [comment]
At app_data folder only .html file but it does not existed?
![image-2](https://user-images.githubusercontent.com/6762312/42391016-19c87e5c-8178-11e8-98d1-a0132bddf2b7.png)

**Comment by lakhdar** [comment]
Sorry , look here https://github.com/lakhdar/LMS/blob/master/Infrastructure.Data.BoundedContext/UnitOfWork/InitialMemorySet.cs you will see users and roles take the admin user
